export const tableHead = [
  { key: "surname", value: "Фамилия" },
  { key: "name", value: "Имя" },
  { key: "patronymic", value: "Отчество" },
  { key: "gender", value: "Пол" },
  { key: "birthDate", value: "Дата рождения" },
  { key: "phoneNumber", value: "Телефон" },
  { key: "snils", value: "СНИЛС" },
  { key: "oms", value: "ОМС" },
  { key: "passport", value: "Паспорт" },
  { key: "registration", value: "Прописка" },
];
export const specialists = [
  "Врач общей практики (терапевт)",
  "Кардиолог",
  "Невролог",
  "Офтальмолог",
  "Гастроэнтеролог",
  "Хирург",
  "Оториноларинголог (ЛОР)",
  "Педиатр",
  "Гинеколог",
  "Уролог",
];

export const Time = [
  { time: "8:00", key: 1 },
  { time: "9:00", key: 2 },
  { time: "10:00", key: 3 },
  { time: "11:00", key: 4 },
  { time: "12:00", key: 5 },
  { time: "13:00", key: 6 },
  { time: "14:00", key: 7 },
  { time: "15:00", key: 8 },
];

export const doctors = [
  {
    id: 0,
    surname: "Тапкин",
    name: "Александр",
    patronymic: "Витальевич",
    specialist: "Кардиолог",
  },
  {
    id: 1,
    surname: "Иванов",
    name: "Иван",
    patronymic: "Иванович",
    specialist: "Терапевт",
  },
  {
    id: 2,
    surname: "Петров",
    name: "Петр",
    patronymic: "Петрович",
    specialist: "Хирург",
  },
  {
    id: 3,
    surname: "Сидоров",
    name: "Сидор",
    patronymic: "Сидорович",
    specialist: "Офтальмолог",
  },
  {
    id: 4,
    surname: "Кузнецов",
    name: "Кузьма",
    patronymic: "Кузьмич",
    specialist: "Невролог",
  },
  {
    id: 5,
    surname: "Попов",
    name: "Павел",
    patronymic: "Павлович",
    specialist: "Стоматолог",
  },
  {
    id: 6,
    surname: "Соколов",
    name: "Сергей",
    patronymic: "Сергеевич",
    specialist: "Педиатр",
  },
  {
    id: 7,
    surname: "Васильев",
    name: "Василий",
    patronymic: "Васильевич",
    specialist: "Гастроэнтеролог",
  },
  {
    id: 8,
    surname: "Смирнов",
    name: "Семен",
    patronymic: "Семенович",
    specialist: "Дерматолог",
  },
  {
    id: 9,
    surname: "Морозов",
    name: "Михаил",
    patronymic: "Михайлович",
    specialist: "Уролог",
  },
];
